apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-centos-datavolume
  name: vm-centos-datavolume
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: centos-dv
    spec:
      pvc:
        volumeMode: Block
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10G
        storageClassName: rook-ceph-block
      source:
        http:
          url: http://172.17.0.1/CentOS-7-x86_64-GenericCloud.qcow2
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: centos-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumevolume
          - disk:
              bus: virtio
            name: cloudinit
        machine:
          type: ""
        resources:
          requests:
            memory: 2G
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: centos-dv
        name: datavolumevolume
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: centos
            chpasswd: { expire: False }
        name: cloudinit
